# **BREAST CANCER DETECTION**

## **PROBLEM STATEMENT**

**TO IDENTIFY WHETHER THE BREAST CANCER IS THE MALIGNANT TUMOR OR BENIGN TUMOR**

In [21]:
import numpy as np                                                              # for using reshape function
import pandas as pd                                                             # for using dataframe

from sklearn.datasets import load_breast_cancer                                 # for loading the breast cancer dataset
from sklearn.preprocessing import StandardScaler                                # for converting the data range(-5, 5)

from keras.models import Sequential                                             # for creating sequential neural network
from keras.layers import Dense                                                  # for adding the layers to the neural network

## **DATA COLLECTION**

In [22]:
data = load_breast_cancer()
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [23]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [24]:
for i in data.keys():
  print(i)
  print(data[i])
  print("---------------------------------------------------------------------------------------")

data
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
---------------------------------------------------------------------------------------
target
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1

## **DATA PRE-PROCESSING**

In [25]:
pd.DataFrame(data['data'], columns=data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [26]:
data['data'] = StandardScaler().fit_transform(data['data'])                     # converting data into the range(-5, 5)

In [27]:
df1 = pd.DataFrame(data['data'], columns=data['feature_names'])
df1

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [28]:
df2 = pd.DataFrame(data['target'], columns=['labels'])
df2

labels
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [29]:
df = pd.concat([df1,df2], axis=1)                                               # combining dataframe df1 and df2
df

mean radius  mean texture  ...  worst fractal dimension  labels
0       1.097064     -2.073335  ...                 1.937015       0
1       1.829821     -0.353632  ...                 0.281190       0
2       1.579888      0.456187  ...                 0.201391       0
3      -0.768909      0.253732  ...                 4.935010       0
4       1.750297     -1.151816  ...                -0.397100       0
..           ...           ...  ...                      ...     ...
564     2.110995      0.721473  ...                -0.709091       0
565     1.704854      2.085134  ...                -0.973978       0
566     0.702284      2.045574  ...                -0.318409       0
567     1.838341      2.336457  ...                 2.219635       0
568    -1.808401      1.221792  ...                -0.751207       1

[569 rows x 31 columns]

In [30]:
df.sample(frac = 1)                                                             # shuffling the data

mean radius  mean texture  ...  worst fractal dimension  labels
42      1.403799      1.284623  ...                 1.100236       0
27      1.273153      0.223480  ...                -0.539518       0
527    -0.507616     -1.633519  ...                -0.444757       1
155    -0.533178     -0.314072  ...                -0.145512       1
110    -1.235545     -0.535144  ...                 0.040685       1
..           ...           ...  ...                      ...     ...
561    -0.831392      2.345765  ...                -1.379622       1
304    -0.757549     -0.262877  ...                -0.419266       1
253     0.901094     -0.514200  ...                -0.156041       0
248    -0.987600      1.380033  ...                -0.137199       1
451     1.551487      1.328837  ...                -1.276549       0

[569 rows x 31 columns]

In [31]:
features = df.values[:,:30]                                                     # getting first 30 columns for features
labels = df.values[:,30:]                                                       # getting the last column for labels

## **TRAINING THE MODEL**

In [32]:
X_train = features[:500]                                                        # splitting 500 data for training
Y_train = labels[:500]

X_val = features[500:535]                                                       # splitting 35 data for validation
Y_val = labels[500:535]

X_test = features[535:]                                                         # splitting 34 data for testing
Y_test = labels[535:]

In [62]:
model = Sequential()                                                            # creating the sequential neural network

model.add(Dense(15, activation='relu', input_dim=30))                           # adding the layers to the neural network
model.add(Dense(10,activation='relu'))
model.add(Dense(5,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [63]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])        # compiling the model to find the errors

In [64]:
model.fit(X_train, Y_train, epochs = 10, batch_size = 5, validation_data=(X_val, Y_val)) # training the model using fit function

Epoch 1/10
100/100 [==============================] - 1s 3ms/step - loss: 0.4858 - accuracy: 0.8040 - val_loss: 0.3415 - val_accuracy: 0.9714
Epoch 2/10
100/100 [==============================] - 0s 2ms/step - loss: 0.2224 - accuracy: 0.9280 - val_loss: 0.1740 - val_accuracy: 1.0000
Epoch 3/10
100/100 [==============================] - 0s 2ms/step - loss: 0.1360 - accuracy: 0.9600 - val_loss: 0.1055 - val_accuracy: 1.0000
Epoch 4/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0996 - accuracy: 0.9740 - val_loss: 0.0785 - val_accuracy: 1.0000
Epoch 5/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0826 - accuracy: 0.9760 - val_loss: 0.0572 - val_accuracy: 1.0000
Epoch 6/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0693 - accuracy: 0.9820 - val_loss: 0.0534 - val_accuracy: 1.0000
Epoch 7/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0599 - accuracy: 0.9860 - val_loss: 0.0452 - val_accuracy: 1.0000
Epoch 

## **EVALUATING THE MODEL**

In [65]:
model.evaluate(X_test, Y_test)                                                  # evaluating the model with test data

2/2 [==============================] - 0s 7ms/step - loss: 0.0519 - accuracy: 1.0000


[0.05194849520921707, 1.0]

In [66]:
model.evaluate(X_val, Y_val)                                                    # evaluating the model with validation data

2/2 [==============================] - 0s 5ms/step - loss: 0.0316 - accuracy: 1.0000


[0.031594421714544296, 1.0]

In [67]:
model.predict(np.reshape(X_test[0],(1,30)))                                     # reshaping the test data to (1,features) to predict the output

array([[1.273327e-06]], dtype=float32)

In [68]:
Y_test[0]                                                                       # finding actual output

array([0.])

In [69]:
for i in range(34):
  sample = X_test[i]
  sample = np.reshape(sample,(1,30))
  if model.predict(sample) > 0.5:
    print("predicted value = benign_tumor")
  else:
    print("predicted value = malignant_tumor")
  if Y_test[i] == 1:
    print("actual value = benign_tumor")
  else:
    print("actual value = malignant_tumor")
  print("---------------------------")

predicted value = malignant_tumor
actual value = malignant_tumor
---------------------------
predicted value = malignant_tumor
actual value = malignant_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
actual value = benign_tumor
---------------------------
predicted value = benign_tumor
